### ISSUE TITLE
Build 500 can't create imagicalmine.yml

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#651]
This happenes after i upgraded from 429 to 500 (I deleted server.properties and pocketmine.yml before that) [It creates imacgicalmine.yml without any stuff in it!
```
[13:01:11] system> -------------------------------------------------------------------------------------------
[13:01:11] system> |  _                       _           _ __  __ _                                         |
[13:01:11] system> | (_)                     (_)         | |  \/  (_)                                        |
[13:01:11] system> |  _ _ __ ___   __ _  __ _ _  ___ __ _| | \  / |_ _ __   ___                              |
[13:01:11] system> | | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \      ImagicalMine 1.0dev    |
[13:01:11] system> | | | | | | | | (_| | (_| | | (_| (_| | | |  | | | | | |  __/                             |
[13:01:11] system> | |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_|  |_|_|_| |_|\___|    for MCPE v0.13.1 alpha   |
[13:01:11] system> |                     __/ |                                                               |
[13:01:11] system> |                    |___/                                                                |
[13:01:11] system> ------------------------------------------------------------------------------------------- 
[13:01:11] system>                                                                                                                         
[13:01:11] system> ImagicalMine is a third-party build of PocketMine-MP, distributed under the LGPL licence

Fatal error: Uncaught exception 'RuntimeException' with message 'yaml_parse(): end of stream reached without finding document 0' in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/utils/Config.php:148
Stack trace:
#0 [internal function]: ExceptionHandler::handler(2, 'yaml_parse(): e...', 'phar:///Users/T...', 148, Array)
#1 phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/utils/Config.php(148): yaml_parse('')
#2 phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/utils/Config.php(85): pocketmine\utils\Config->load('/Users/Tim/Desk...', 2, Array)
#3 phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/katana/Katana.php(104): pocketmine\utils\Config->__construct('/Users/Tim/Desk...', 2, Array)
#4 phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/katana/Katana.php(79): pocketmine\katana\Katana->initConfig()
#5 phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 148
```
Really? Why do you have to break EVERYTHING?
(You broke Slapper again)

**Comment by PocketKiller** [comment]
my problem is that it just generates
```
---
[]
...

**Comment by robske110** [comment]
Why Why? Why are you messing with the MainLogger if there are so many other bugs to fix?

**Comment by keithkfng** [comment]
Thought so. I can't fix it now cos I'm nearly half-asleep XD
@PocketKiller would you be so kind as I check in with the error? Thanks.

**Comment by robske110** [comment]
Why do you even TRY to mess around with that stuff. I would never try to upgrade if the bug #592 doesn't exist!

**Comment by keithkfng** [comment]
If you're so angry, go try fixing the bugs yourself. You know it takes time to figure out what's causing it? Everytime you get that error it's because of a different file. If you think we're miracle workers - guess what? We're not -_-

**Comment by keithkfng** [comment]
@PocketKiller Never mind... Figured what the problem was. It was because you didn't have a source folder like Katana did here - https://github.com/ImagicalCorp/ImagicalMine/commit/1f2a2ab28927f48423574088c608a65aa0a80b7b

**Comment by robske110** [comment]
I know whats causing it: the stupid commits who made this mess
//I am realy angry right now, i will write nothing until tomorrow anymore :) I will look through the code though...

**Comment by keithkfng** [comment]
Alright... How's this - https://github.com/ImagicalCorp/ImagicalMine/commit/9d29bcda2da1e5c840b17b828839aadb89d144b4
Couldn't find another solution...

**Comment by robske110** [comment]
Ok, the issue is that the server tries to access the NOT-Generated config file

**Comment by robske110** [comment]
Maybe that will generate it (TESTING NOW)

**Comment by robske110** [comment]
Nope is still crashing

**Comment by robske110** [comment]
Where is pocketmine.yml created?

**Comment by keithkfng** [comment]
After lots of testing - this issue is fixed...
