### ISSUE TITLE
it crast on android ): plz help me

### ISSUE THREAD

**Issue by lolcraftboy14** [ImagicalCorp/ImagicalMine#663]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [06:22:36] warning> Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [06:22:36] system> -------------------------------------------------------------------------------------------
[Server] [06:22:36] system> | _ _ _ __ __ _ |
[Server] [06:22:36] system> | (_) (_) | | \/ (_) |
[Server] [06:22:36] system> | _ _ __ ___ __ _ __ _ _ ___ __ _| | \ / |_ _ __ ___ |
[Server] [06:22:36] system> | | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ ImagicalMine 1.0dev |
[Server] [06:22:36] system> | | | | | | | | (_| | (_| | | (_| (_| | | | | | | | | | __/ |
[Server] [06:22:36] system> | |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_| |_|_|_| |_|\___| for MCPE v0.13.1 alpha |
[Server] [06:22:36] system> | __/ | |
[Server] [06:22:36] system> | |___/ |
[Server] [06:22:36] system> ------------------------------------------------------------------------------------------- 
[Server] [06:22:36] system> 
[Server] [06:22:36] system> ImagicalMine is a third-party build of PocketMine-MP, distributed under the LGPL licence
[Server] 
[Server] Fatal error: Uncaught exception 'RuntimeException' with message 'file_get_contents(/storage/emulated/0/PocketMine/src/pocketmine/resources/imagicalmine.yml): failed to open stream: No such file or directory' in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/katana/Katana.php:101
[Server] Stack trace:
[Server] #0 [internal function]: ExceptionHandler::handler(2, 'file_get_conten...', 'phar:///storage...', 101, Array)
[Server] #1 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/katana/Katana.php(101): file_get_contents('/storage/emulat...')
[Server] #2 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/katana/Katana.php(79): pocketmine\katana\Katana->initConfig()
[Server] #3 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/Server.php(1577): pocketmine\katana\Katana->__construct(Object(pocketmine\Server))
[Server] #4 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php(469): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object( in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/katana/Katana.php on line 101

**Comment by lolcraftboy14** [comment]
Y use latest build  512

**Comment by lolcraftboy14** [comment]
Oeps old news ):
